-- 코드를 입력하세요
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('MILK', 'YOGURT')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) >= 2
;

SELECT DISTINCT A.CART_ID
FROM (
    SELECT A.CART_ID, A.NAME PRODUCT1, B.NAME PRODUCT2
    FROM CART_PRODUCTS A
    JOIN CART_PRODUCTS B
    ON A.CART_ID = B.CART_ID
) A
WHERE (PRODUCT1 = 'YOGURT' AND PRODUCT2='MILK')
    OR (PRODUCT1='MILK' AND PRODUCT2='YOGURT')
;