-- 코드를 입력하세요
SELECT 
    UGU.USER_ID, 
    UGU.NICKNAME, 
    CONCAT(UGU.CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소',
    CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER UGU
JOIN (
    SELECT 
        WRITER_ID, 
        COUNT(BOARD_ID) AS BOARD_CNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING BOARD_CNT >= 3
) UGB
ON UGU.USER_ID = UGB.WRITER_ID
ORDER BY 1 DESC
;