-- 코드를 입력하세요
SELECT CAR_ID,
    CASE
        WHEN AVG(DATEDIFF(END_DATE, START_DATE)+1) >= 7
            THEN ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1)
    END AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION IS NOT NULL
ORDER BY 2 DESC, 1 DESC
;