-- 코드를 작성해주세요
SELECT FI.FISH_COUNT, FNI.FISH_NAME
FROM (SELECT COUNT(FISH_TYPE) AS FISH_COUNT, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE) FI
JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI.FISH_COUNT DESC;