-- 코드를 입력하세요.
SELECT HG.EMP_NO,
    HE.EMP_NAME,
    HG.GRADE,
    CASE WHEN HG.GRADE = 'S' THEN HE.SAL*0.2
        WHEN HG.GRADE = 'A' THEN HE.SAL*0.15
        WHEN HG.GRADE = 'B' THEN HE.SAL*0.1
        ELSE 0
    END BONUS
FROM (
    SELECT EMP_NO, 
    CASE WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO
) HG
LEFT JOIN HR_EMPLOYEES HE
    ON HG.EMP_NO = HE.EMP_NO
ORDER BY 1
;