SELECT HG.EMP_NO,
    HE.EMP_NAME,
    CASE WHEN HG.SCORE >= 96 THEN 'S'
        WHEN HG.SCORE >= 90 THEN 'A'
        WHEN HG.SCORE >= 80 THEN 'B'
        ELSE 'C'
    END GRADE,
    CASE WHEN HG.SCORE >= 96 THEN HE.SAL*0.2
        WHEN HG.SCORE >= 90 THEN HE.SAL*0.15
        WHEN HG.SCORE >= 80 THEN HE.SAL*0.1
        ELSE 0
    END BONUS
FROM (
    SELECT EMP_NO, AVG(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) HG
LEFT JOIN HR_EMPLOYEES HE
    ON HG.EMP_NO = HE.EMP_NO
ORDER BY 1
;