SELECT A.ITEM_ID, II2.ITEM_NAME, II2.RARITY
FROM (
    SELECT IT.PARENT_ITEM_ID, II.ITEM_NAME, II.RARITY, IT.ITEM_ID
    FROM ITEM_TREE IT
    JOIN ITEM_INFO II
    ON IT.PARENT_ITEM_ID = II.ITEM_ID
    WHERE RARITY = 'RARE'
) A
JOIN ITEM_INFO II2
ON A.ITEM_ID = II2.ITEM_ID
ORDER BY 1 DESC
;