-- 코드를 작성해주세요
SELECT YEAR(ED.DIFFERENTIATION_DATE) YEAR, 
    (EDY.MAX_SIZE - ED.SIZE_OF_COLONY) YEAR_DEV,
    ED.ID
FROM ECOLI_DATA ED
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) EDY
ON YEAR(ED.DIFFERENTIATION_DATE) = EDY.YEAR
ORDER BY 1 ASC, 2 ASC
;