-- 코드를 입력하세요
SELECT DISTINCT RH.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
JOIN CAR_RENTAL_COMPANY_CAR C
    ON RH.CAR_ID = C.CAR_ID
        AND C.CAR_TYPE = '세단'
WHERE MONTH(RH.START_DATE) = 10
ORDER BY RH.CAR_ID DESC
;
