-- 코드를 작성해주세요
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) MFI
ON FI.FISH_TYPE = MFI.FISH_TYPE
    AND FI.LENGTH = MFI.MAX_LENGTH
JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
ORDER BY 1
;