-- 코드를 작성해주세요
SELECT FML.ID, FNI.FISH_NAME, FML.LENGTH
FROM(
    SELECT FI1.ID, FI1.FISH_TYPE, FI1.LENGTH
    FROM FISH_INFO FI1, (
        SELECT FISH_TYPE, MAX(LENGTH) LENGTH
        FROM FISH_INFO 
        GROUP BY FISH_TYPE
        ) FI2
    WHERE FI1.FISH_TYPE = FI2.FISH_TYPE 
        AND FI1.LENGTH = FI2.LENGTH
) FML
JOIN FISH_NAME_INFO FNI 
    ON FML.FISH_TYPE = FNI.FISH_TYPE
ORDER BY 1
;
