-- 코드를 작성해주세요
SELECT COUNT(ID) FISH_COUNT,
    MAX(LENGTH) MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM (
        SELECT FISH_TYPE, AVG(CASE WHEN LENGTH IS NULL THEN 10
                    ELSE LENGTH
               END) AVG_LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) FIG
    WHERE FIG.AVG_LENGTH >= 33 
)
GROUP BY FISH_TYPE
ORDER BY 3
;
